# autoscaler-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-service-account
  namespace: microservices-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoscaler-role
subjects:
- kind: ServiceAccount
  name: autoscaler-service-account
  namespace: microservices-demo